// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddTeamPermissions(ctx context.Context, arg AddTeamPermissionsParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRefreshToken(ctx context.Context, userID uuid.UUID) (*string, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	InviteToTeam(ctx context.Context, arg InviteToTeamParams) error
	NewTeam(ctx context.Context, arg NewTeamParams) (Team, error)
	RemoveRefreshToken(ctx context.Context, userID uuid.UUID) error
	ResondToTeamInvitation(ctx context.Context, arg ResondToTeamInvitationParams) error
	UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error
}

var _ Querier = (*Queries)(nil)
