// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserToProject(ctx context.Context, arg AddUserToProjectParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRefreshToken(ctx context.Context, userID uuid.UUID) (*string, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	InviteToProject(ctx context.Context, arg InviteToProjectParams) error
	NewProject(ctx context.Context, arg NewProjectParams) (Project, error)
	RemoveRefreshToken(ctx context.Context, userID uuid.UUID) error
	ResondToProjectInvitation(ctx context.Context, arg ResondToProjectInvitationParams) error
	UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error
}

var _ Querier = (*Queries)(nil)
